things_dict = {
    'things': 'things',
    'indoor-super-things': 'things',
    'outdoor-super-things': 'things',
    'person-things': 'outdoor-super-things',
    'vehicle-things': 'outdoor-super-things',
    'outdoor-things': 'outdoor-super-things',
    'animal-things': 'outdoor-super-things',
    'accessory-things': 'outdoor-super-things',
    'sports-things': 'outdoor-super-things',
    'kitchen-things': 'indoor-super-things',
    'food-things': 'indoor-super-things',
    'furniture-things': 'indoor-super-things',
    'electronic-things': 'indoor-super-things',
    'appliance-things': 'indoor-super-things',
    'indoor-things': 'indoor-super-things',
    'person': 'person-things',
    'bicycle': 'vehicle-things',
    'car': 'vehicle-things',
    'motorcycle': 'vehicle-things',
    'airplane': 'vehicle-things',
    'bus': 'vehicle-things',
    'train': 'vehicle-things',
    'truck': 'vehicle-things',
    'boat': 'vehicle-things',
    'traffic light': 'outdoor-things',
    'fire hydrant': 'outdoor-things',
    'street sign': 'outdoor-things',
    'stop sign': 'outdoor-things',
    'parking meter': 'outdoor-things',
    'bench': 'outdoor-things',
    'bird': 'animal-things',
    'cat': 'animal-things',
    'dog': 'animal-things',
    'horse': 'animal-things',
    'sheep': 'animal-things',
    'cow': 'animal-things',
    'elephant': 'animal-things',
    'bear': 'animal-things',
    'zebra': 'animal-things',
    'giraffe': 'animal-things',
    'hat': 'accessory-things',
    'backpack': 'accessory-things',
    'umbrella': 'accessory-things',
    'shoe': 'accessory-things',
    'eye glasses': 'accessory-things',
    'handbag': 'accessory-things',
    'tie': 'accessory-things',
    'suitcase': 'accessory-things',
    'frisbee': 'sports-things',
    'skis': 'sports-things',
    'snowboard': 'sports-things',
    'sports ball': 'sports-things',
    'kite': 'sports-things',
    'baseball bat': 'sports-things',
    'baseball glove': 'sports-things',
    'skateboard': 'sports-things',
    'surfboard': 'sports-things',
    'tennis racket': 'sports-things',
    'bottle': 'kitchen-things',
    'plate': 'kitchen-things',
    'wine glass': 'kitchen-things',
    'cup': 'kitchen-things',
    'fork': 'kitchen-things',
    'knife': 'kitchen-things',
    'spoon': 'kitchen-things',
    'bowl': 'kitchen-things',
    'banana': 'food-things',
    'apple': 'food-things',
    'sandwich': 'food-things',
    'orange': 'food-things',
    'broccoli': 'food-things',
    'carrot': 'food-things',
    'hot dog': 'food-things',
    'pizza': 'food-things',
    'donut': 'food-things',
    'cake': 'food-things',
    'chair': 'furniture-things',
    'couch': 'furniture-things',
    'potted plant': 'furniture-things',
    'bed': 'furniture-things',
    'mirror': 'furniture-things',
    'dining table': 'furniture-things',
    'window': 'furniture-things',
    'desk': 'furniture-things',
    'toilet': 'furniture-things',
    'door': 'furniture-things',
    'tv': 'electronic-things',
    'laptop': 'electronic-things',
    'mouse': 'electronic-things',
    'remote': 'electronic-things',
    'keyboard': 'electronic-things',
    'cell phone': 'electronic-things',
    'microwave': 'appliance-things',
    'oven': 'appliance-things',
    'toaster': 'appliance-things',
    'sink': 'appliance-things',
    'refrigerator': 'appliance-things',
    'blender': 'appliance-things',
    'book': 'indoor-things',
    'clock': 'indoor-things',
    'vase': 'indoor-things',
    'scissors': 'indoor-things',
    'teddy bear': 'indoor-things',
    'hair drier': 'indoor-things',
    'toothbrush': 'indoor-things',
    'hair brush': 'indoor-things'

}

stuff_dict = {
    'stuff': 'stuff',
    'indoor-super-stuff': 'stuff',
    'outdoor-super-stuff': 'stuff',
    'rawmaterial-stuff': 'indoor-super-stuff',
    'wall-stuff': 'indoor-super-stuff',
    'ceiling-stuff': 'indoor-super-stuff',
    'floor-stuff': 'indoor-super-stuff',
    'window-stuff': 'indoor-super-stuff',
    'furniture-stuff': 'indoor-super-stuff',
    'textile-stuff': 'indoor-super-stuff',
    'food-stuff': 'indoor-super-stuff',
    'building-stuff': 'outdoor-super-stuff',
    'structural-stuff': 'outdoor-super-stuff',
    'plant-stuff': 'outdoor-super-stuff',
    'sky-stuff': 'outdoor-super-stuff',
    'solid-stuff': 'outdoor-super-stuff',
    'ground-stuff': 'outdoor-super-stuff',
    'water-stuff': 'outdoor-super-stuff',
    'cardboard': 'rawmaterial-stuff',
    'paper': 'rawmaterial-stuff',
    'plastic': 'rawmaterial-stuff',
    'metal': 'rawmaterial-stuff',
    'wall-tile': 'wall-stuff',
    'wall-panel': 'wall-stuff',
    'wall-wood': 'wall-stuff',
    'wall-brick': 'wall-stuff',
    'wall-stone': 'wall-stuff',
    'wall-concrete': 'wall-stuff',
    'wall-other': 'wall-stuff',
    'ceiling-tile': 'ceiling-stuff',
    'ceiling-other': 'ceiling-stuff',
    'carpet': 'floor-stuff',
    'floor-tile': 'floor-stuff',
    'floor-wood': 'floor-stuff',
    'floor-marble': 'floor-stuff',
    'floor-stone': 'floor-stuff',
    'floor-other': 'floor-stuff',
    'window-blind': 'window-stuff',
    'window-other': 'window-stuff',
    'door-stuff': 'furniture-stuff',
    'desk-stuff': 'furniture-stuff',
    'table': 'furniture-stuff',
    'shelf': 'furniture-stuff',
    'cabinet': 'furniture-stuff',
    'cupboard': 'furniture-stuff',
    'mirror-stuff': 'furniture-stuff',
    'counter': 'furniture-stuff',
    'light': 'furniture-stuff',
    'stairs': 'furniture-stuff',
    'furniture-other': 'furniture-stuff',
    'rug': 'textile-stuff',
    'mat': 'textile-stuff',
    'towel': 'textile-stuff',
    'napkin': 'textile-stuff',
    'clothes': 'textile-stuff',
    'cloth': 'textile-stuff',
    'curtain': 'textile-stuff',
    'blanket': 'textile-stuff',
    'pillow': 'textile-stuff',
    'banner': 'textile-stuff',
    'textile-other': 'textile-stuff',
    'fruit': 'food-stuff',
    'salad': 'food-stuff',
    'vegetable': 'food-stuff',
    'food-other': 'food-stuff',
    'house': 'building-stuff',
    'skyscraper': 'building-stuff',
    'bridge': 'building-stuff',
    'tent': 'building-stuff',
    'roof': 'building-stuff',
    'building-other': 'building-stuff',
    'fence': 'structural-stuff',
    'cage': 'structural-stuff',
    'net': 'structural-stuff',
    'railing': 'structural-stuff',
    'structural-other': 'structural-stuff',
    'grass': 'plant-stuff',
    'tree': 'plant-stuff',
    'bush': 'plant-stuff',
    'leaves': 'plant-stuff',
    'flower': 'plant-stuff',
    'branch': 'plant-stuff',
    'moss': 'plant-stuff',
    'straw': 'plant-stuff',
    'plant-other': 'plant-stuff',
    'clouds': 'sky-stuff',
    'sky-other': 'sky-stuff',
    'wood': 'solid-stuff',
    'rock': 'solid-stuff',
    'stone': 'solid-stuff',
    'mountain': 'solid-stuff',
    'hill': 'solid-stuff',
    'solid-other': 'solid-stuff',
    'sand': 'ground-stuff',
    'snow': 'ground-stuff',
    'dirt': 'ground-stuff',
    'mud': 'ground-stuff',
    'gravel': 'ground-stuff',
    'road': 'ground-stuff',
    'pavement': 'ground-stuff',
    'railroad': 'ground-stuff',
    'platform': 'ground-stuff',
    'playingfield': 'ground-stuff',
    'ground-other': 'ground-stuff',
    'fog': 'water-stuff',
    'river': 'water-stuff',
    'sea': 'water-stuff',
    'waterdrops': 'water-stuff',
    'water-other': 'water-stuff',
}

all_dict = {
    'stuff': 'stuff',
    'indoor': 'stuff',
    'outdoor': 'stuff',
    'rawmaterial': 'indoor',
    'wall': 'indoor',
    'ceiling': 'indoor',
    'floor': 'indoor',
    'window': 'indoor',
    'furniture': 'indoor',
    'textile': 'indoor',
    'food': 'indoor',
    'building': 'outdoor',
    'structural': 'outdoor',
    'plant': 'outdoor',
    'sky': 'outdoor',
    'solid': 'outdoor',
    'ground': 'outdoor',
    'water': 'outdoor',
    'cardboard': 'rawmaterial',
    'paper': 'rawmaterial',
    'plastic': 'rawmaterial',
    'metal': 'rawmaterial',
    'wall-tile': 'wall',
    'wall-panel': 'wall',
    'wall-wood': 'wall',
    'wall-brick': 'wall',
    'wall-stone': 'wall',
    'wall-concrete': 'wall',
    'wall-other': 'wall',
    'ceiling-tile': 'ceiling',
    'ceiling-other': 'ceiling',
    'carpet': 'floor',
    'floor-tile': 'floor',
    'floor-wood': 'floor',
    'floor-marble': 'floor',
    'floor-stone': 'floor',
    'floor-other': 'floor',
    'window-blind': 'window',
    'window-other': 'window',
    'door': 'furniture',
    'desk': 'furniture',
    'table': 'furniture',
    'shelf': 'furniture',
    'cabinet': 'furniture',
    'cupboard': 'furniture',
    'mirror': 'furniture',
    'counter': 'furniture',
    'light': 'furniture',
    'stairs': 'furniture',
    'furniture-other': 'furniture',
    'rug': 'textile',
    'mat': 'textile',
    'towel': 'textile',
    'napkin': 'textile',
    'clothes': 'textile',
    'cloth': 'textile',
    'curtain': 'textile',
    'blanket': 'textile',
    'pillow': 'textile',
    'banner': 'textile',
    'textile-other': 'textile',
    'fruit': 'food',
    'salad': 'food',
    'vegetable': 'food',
    'food-other': 'food',
    'house': 'building',
    'skyscraper': 'building',
    'bridge': 'building',
    'tent': 'building',
    'roof': 'building',
    'building-other': 'building',
    'fence': 'structural',
    'cage': 'structural',
    'net': 'structural',
    'railing': 'structural',
    'structural-other': 'structural',
    'grass': 'plant',
    'tree': 'plant',
    'bush': 'plant',
    'leaves': 'plant',
    'flower': 'plant',
    'branch': 'plant',
    'moss': 'plant',
    'straw': 'plant',
    'plant-other': 'plant',
    'clouds': 'sky',
    'sky-other': 'sky',
    'wood': 'solid',
    'rock': 'solid',
    'stone': 'solid',
    'mountain': 'solid',
    'hill': 'solid',
    'solid-other': 'solid',
    'sand': 'ground',
    'snow': 'ground',
    'dirt': 'ground',
    'mud': 'ground',
    'gravel': 'ground',
    'road': 'ground',
    'pavement': 'ground',
    'railroad': 'ground',
    'platform': 'ground',
    'playingfield': 'ground',
    'ground-other': 'ground',
    'fog': 'water',
    'river': 'water',
    'sea': 'water',
    'waterdrops': 'water',
    'water-other': 'water',
    'things': 'things',
    'indoor': 'things',
    'outdoor': 'things',
    'person': 'outdoor',
    'vehicle': 'outdoor',
    'outdoor': 'outdoor',
    'animal': 'outdoor',
    'accessory': 'outdoor',
    'sports': 'outdoor',
    'kitchen': 'indoor',
    'food': 'indoor',
    'furniture': 'indoor',
    'electronic': 'indoor',
    'appliance': 'indoor',
    'indoor': 'indoor',
    'person': 'person',
    'bicycle': 'vehicle',
    'car': 'vehicle',
    'motorcycle': 'vehicle',
    'airplane': 'vehicle',
    'bus': 'vehicle',
    'train': 'vehicle',
    'truck': 'vehicle',
    'boat': 'vehicle',
    'traffic light': 'outdoor',
    'fire hydrant': 'outdoor',
    'street sign': 'outdoor',
    'stop sign': 'outdoor',
    'parking meter': 'outdoor',
    'bench': 'outdoor',
    'bird': 'animal',
    'cat': 'animal',
    'dog': 'animal',
    'horse': 'animal',
    'sheep': 'animal',
    'cow': 'animal',
    'elephant': 'animal',
    'bear': 'animal',
    'zebra': 'animal',
    'giraffe': 'animal',
    'hat': 'accessory',
    'backpack': 'accessory',
    'umbrella': 'accessory',
    'shoe': 'accessory',
    'eye glasses': 'accessory',
    'handbag': 'accessory',
    'tie': 'accessory',
    'suitcase': 'accessory',
    'frisbee': 'sports',
    'skis': 'sports',
    'snowboard': 'sports',
    'sports ball': 'sports',
    'kite': 'sports',
    'baseball bat': 'sports',
    'baseball glove': 'sports',
    'skateboard': 'sports',
    'surfboard': 'sports',
    'tennis racket': 'sports',
    'bottle': 'kitchen',
    'plate': 'kitchen',
    'wine glass': 'kitchen',
    'cup': 'kitchen',
    'fork': 'kitchen',
    'knife': 'kitchen',
    'spoon': 'kitchen',
    'bowl': 'kitchen',
    'banana': 'food',
    'apple': 'food',
    'sandwich': 'food',
    'orange': 'food',
    'broccoli': 'food',
    'carrot': 'food',
    'hot dog': 'food',
    'pizza': 'food',
    'donut': 'food',
    'cake': 'food',
    'chair': 'furniture',
    'couch': 'furniture',
    'potted plant': 'furniture',
    'bed': 'furniture',
    'mirror': 'furniture',
    'dining table': 'furniture',
    'window': 'furniture',
    'desk': 'furniture',
    'toilet': 'furniture',
    'door': 'furniture',
    'tv': 'electronic',
    'laptop': 'electronic',
    'mouse': 'electronic',
    'remote': 'electronic',
    'keyboard': 'electronic',
    'cell phone': 'electronic',
    'microwave': 'appliance',
    'oven': 'appliance',
    'toaster': 'appliance',
    'sink': 'appliance',
    'refrigerator': 'appliance',
    'blender': 'appliance',
    'book': 'indoor',
    'clock': 'indoor',
    'vase': 'indoor',
    'scissors': 'indoor',
    'teddy bear': 'indoor',
    'hair drier': 'indoor',
    'toothbrush': 'indoor',
    'hair brush': 'indoor',
}

filter_classes = {
    0: 'unlabeled',
    1: 'person',
    2: 'bicycle',
    3: 'car',
    4: 'motorcycle',
    5: 'airplane',
    6: 'bus',
    7: 'train',
    8: 'truck',
    9: 'boat',
    10: 'traffic light',
    11: 'fire hydrant',
    13: 'stop sign',
    14: 'parking meter',
    15: 'bench',
    16: 'bird',
    17: 'cat',
    18: 'dog',
    19: 'horse',
    20: 'sheep',
    21: 'cow',
    22: 'elephant',
    23: 'bear',
    24: 'zebra',
    25: 'giraffe',
    27: 'backpack',
    28: 'umbrella',
    31: 'handbag',
    32: 'tie',
    33: 'suitcase',
    34: 'frisbee',
    35: 'skis',
    36: 'snowboard',
    37: 'sports ball',
    38: 'kite',
    39: 'baseball bat',
    40: 'baseball glove',
    41: 'skateboard',
    42: 'surfboard',
    43: 'tennis racket',
    44: 'bottle',
    46: 'wine glass',
    47: 'cup',
    48: 'fork',
    49: 'knife',
    50: 'spoon',
    51: 'bowl',
    52: 'banana',
    53: 'apple',
    54: 'sandwich',
    55: 'orange',
    56: 'broccoli',
    57: 'carrot',
    58: 'hot dog',
    59: 'pizza',
    60: 'donut',
    61: 'cake',
    62: 'chair',
    63: 'couch',
    64: 'potted plant',
    65: 'bed',
    67: 'dining table',
    70: 'toilet',
    72: 'tv',
    73: 'laptop',
    74: 'mouse',
    75: 'remote',
    76: 'keyboard',
    77: 'cell phone',
    78: 'microwave',
    79: 'oven',
    80: 'toaster',
    81: 'sink',
    82: 'refrigerator',
    84: 'book',
    85: 'clock',
    86: 'vase',
    87: 'scissors',
    88: 'teddy bear',
    89: 'hair drier',
    90: 'toothbrush',
    92: 'banner',
    93: 'blanket',
    94: 'branch',
    95: 'bridge',
    96: 'building-other',
    97: 'bush',
    98: 'cabinet',
    99: 'cage',
    100: 'cardboard',
    101: 'carpet',
    102: 'ceiling-other',
    103: 'ceiling-tile',
    104: 'cloth',
    105: 'clothes',
    106: 'clouds',
    107: 'counter',
    108: 'cupboard',
    109: 'curtain',
    110: 'desk-stuff',
    111: 'dirt',
    112: 'door-stuff',
    113: 'fence',
    114: 'floor-marble',
    115: 'floor-other',
    116: 'floor-stone',
    117: 'floor-tile',
    118: 'floor-wood',
    119: 'flower',
    120: 'fog',
    121: 'food-other',
    122: 'fruit',
    123: 'furniture-other',
    124: 'grass',
    125: 'gravel',
    126: 'ground-other',
    127: 'hill',
    128: 'house',
    129: 'leaves',
    130: 'light',
    131: 'mat',
    132: 'metal',
    133: 'mirror-stuff',
    134: 'moss',
    135: 'mountain',
    136: 'mud',
    137: 'napkin',
    138: 'net',
    139: 'paper',
    140: 'pavement',
    141: 'pillow',
    142: 'plant-other',
    143: 'plastic',
    144: 'platform',
    145: 'playingfield',
    146: 'railing',
    147: 'railroad',
    148: 'river',
    149: 'road',
    150: 'rock',
    151: 'roof',
    152: 'rug',
    153: 'salad',
    154: 'sand',
    155: 'sea',
    156: 'shelf',
    157: 'sky-other',
    158: 'skyscraper',
    159: 'snow',
    160: 'solid-other',
    161: 'stairs',
    162: 'stone',
    163: 'straw',
    164: 'structural-other',
    165: 'table',
    166: 'tent',
    167: 'textile-other',
    168: 'towel',
    169: 'tree',
    170: 'vegetable',
    171: 'wall-brick',
    172: 'wall-concrete',
    173: 'wall-other',
    174: 'wall-panel',
    175: 'wall-stone',
    176: 'wall-tile',
    177: 'wall-wood',
    178: 'water-other',
    179: 'waterdrops',
    180: 'window-blind',
    181: 'window-other',
    182: 'wood',
    183: 'other'
}

filter_classes_map = {
    'unlabeled': 0,
    'person': 1,
    'bicycle': 2,
    'car': 3,
    'motorcycle': 4,
    'airplane': 5,
    'bus': 6,
    'train': 7,
    'truck': 8,
    'boat': 9,
    'traffic light': 10,
    'fire hydrant': 11,
    'stop sign': 13,
    'parking meter': 14,
    'bench': 15,
    'bird': 16,
    'cat': 17,
    'dog': 18,
    'horse': 19,
    'sheep': 20,
    'cow': 21,
    'elephant': 22,
    'bear': 23,
    'zebra': 24,
    'giraffe': 25,
    'backpack': 27,
    'umbrella': 28,
    'handbag': 31,
    'tie': 32,
    'suitcase': 33,
    'frisbee': 34,
    'skis': 35,
    'snowboard': 36,
    'sports ball': 37,
    'kite': 38,
    'baseball bat': 39,
    'baseball glove': 40,
    'skateboard': 41,
    'surfboard': 42,
    'tennis racket': 43,
    'bottle': 44,
    'wine glass': 46,
    'cup': 47,
    'fork': 48,
    'knife': 49,
    'spoon': 50,
    'bowl': 51,
    'banana': 52,
    'apple': 53,
    'sandwich': 54,
    'orange': 55,
    'broccoli': 56,
    'carrot': 57,
    'hot dog': 58,
    'pizza': 59,
    'donut': 60,
    'cake': 61,
    'chair': 62,
    'couch': 63,
    'potted plant': 64,
    'bed': 65,
    'dining table': 67,
    'toilet': 70,
    'tv': 72,
    'laptop': 73,
    'mouse': 74,
    'remote': 75,
    'keyboard': 76,
    'cell phone': 77,
    'microwave': 78,
    'oven': 79,
    'toaster': 80,
    'sink': 81,
    'refrigerator': 82,
    'book': 84,
    'clock': 85,
    'vase': 86,
    'scissors': 87,
    'teddy bear': 88,
    'hair drier': 89,
    'toothbrush': 90,
    'banner': 92,
    'blanket': 93,
    'branch': 94,
    'bridge': 95,
    'building-other': 96,
    'bush': 97,
    'cabinet': 98,
    'cage': 99,
    'cardboard': 100,
    'carpet': 101,
    'ceiling-other': 102,
    'ceiling-tile': 103,
    'cloth': 104,
    'clothes': 105,
    'clouds': 106,
    'counter': 107,
    'cupboard': 108,
    'curtain': 109,
    'desk-stuff': 110,
    'dirt': 111,
    'door-stuff': 112,
    'fence': 113,
    'floor-marble': 114,
    'floor-other': 115,
    'floor-stone': 116,
    'floor-tile': 117,
    'floor-wood': 118,
    'flower': 119,
    'fog': 120,
    'food-other': 121,
    'fruit': 122,
    'furniture-other': 123,
    'grass': 124,
    'gravel': 125,
    'ground-other': 126,
    'hill': 127,
    'house': 128,
    'leaves': 129,
    'light': 130,
    'mat': 131,
    'metal': 132,
    'mirror-stuff': 133,
    'moss': 134,
    'mountain': 135,
    'mud': 136,
    'napkin': 137,
    'net': 138,
    'paper': 139,
    'pavement': 140,
    'pillow': 141,
    'plant-other': 142,
    'plastic': 143,
    'platform': 144,
    'playingfield': 145,
    'railing': 146,
    'railroad': 147,
    'river': 148,
    'road': 149,
    'rock': 150,
    'roof': 151,
    'rug': 152,
    'salad': 153,
    'sand': 154,
    'sea': 155,
    'shelf': 156,
    'sky-other': 157,
    'skyscraper': 158,
    'snow': 159,
    'solid-other': 160,
    'stairs': 161,
    'stone': 162,
    'straw': 163,
    'structural-other': 164,
    'table': 165,
    'tent': 166,
    'textile-other': 167,
    'towel': 168,
    'tree': 169,
    'vegetable': 170,
    'wall-brick': 171,
    'wall-concrete': 172,
    'wall-other': 173,
    'wall-panel': 174,
    'wall-stone': 175,
    'wall-tile': 176,
    'wall-wood': 177,
    'water-other': 178,
    'waterdrops': 179,
    'window-blind': 180,
    'window-other': 181,
    'wood': 182,
    'other': 183
}

COLOR_MAP = [
    [0, 0, 0],
    [131, 242, 30],
    [134, 241, 28],
    [137, 239, 26],
    [140, 238, 24],
    [143, 236, 23],
    [146, 235, 21],
    [149, 233, 19],
    [152, 231, 18],
    [155, 229, 16],
    [158, 228, 15],
    [161, 226, 14],
    [164, 224, 12],
    [167, 222, 11],
    [170, 220, 10],
    [173, 217, 9],
    [176, 215, 8],
    [178, 213, 7],
    [181, 211, 6],
    [184, 208, 5],
    [187, 206, 4],
    [189, 204, 4],
    [192, 201, 3],
    [195, 199, 3],
    [197, 196, 2],
    [200, 193, 2],
    [202, 191, 1],
    [205, 188, 1],
    [207, 185, 1],
    [209, 183, 1],
    [212, 180, 1],
    [214, 177, 1],
    [216, 174, 1],
    [218, 171, 1],
    [221, 169, 2],
    [223, 166, 2],
    [225, 163, 2],
    [227, 160, 3],
    [228, 157, 4],
    [230, 154, 4],
    [232, 151, 5],
    [234, 148, 6],
    [235, 145, 7],
    [237, 142, 7],
    [239, 139, 8],
    [240, 136, 9],
    [241, 133, 11],
    [243, 130, 12],
    [244, 127, 13],
    [245, 124, 14],
    [246, 121, 16],
    [247, 118, 17],
    [248, 115, 19],
    [249, 111, 20],
    [250, 108, 22],
    [251, 105, 24],
    [252, 102, 26],
    [252, 99, 27],
    [253, 97, 29],
    [253, 94, 31],
    [254, 91, 33],
    [254, 88, 35],
    [255, 85, 37],
    [255, 82, 39],
    [255, 79, 42],
    [255, 76, 44],
    [255, 74, 46],
    [255, 71, 49],
    [255, 68, 51],
    [255, 66, 53],
    [254, 63, 56],
    [254, 60, 58],
    [253, 58, 61],
    [253, 55, 64],
    [252, 53, 66],
    [252, 50, 69],
    [251, 48, 72],
    [250, 46, 74],
    [249, 43, 77],
    [248, 41, 80],
    [247, 39, 83],
    [246, 37, 86],
    [245, 35, 89],
    [244, 33, 92],
    [243, 31, 94],
    [241, 29, 97],
    [240, 27, 100],
    [238, 25, 103],
    [237, 23, 106],
    [235, 22, 109],
    [234, 20, 112],
    [232, 18, 115],
    [230, 17, 118],
    [228, 15, 122],
    [226, 14, 125],
    [224, 13, 128],
    [222, 11, 131],
    [220, 10, 134],
    [218, 9, 137],
    [216, 8, 140],
    [214, 7, 143],
    [212, 6, 146],
    [209, 5, 149],
    [207, 5, 152],
    [204, 4, 155],
    [202, 3, 158],
    [199, 3, 161],
    [197, 2, 164],
    [194, 2, 167],
    [192, 2, 169],
    [189, 1, 172],
    [186, 1, 175],
    [184, 1, 178],
    [181, 1, 181],
    [178, 1, 184],
    [175, 1, 186],
    [172, 1, 189],
    [170, 2, 192],
    [167, 2, 194],
    [164, 2, 197],
    [161, 3, 199],
    [158, 3, 202],
    [155, 4, 204],
    [152, 5, 207],
    [149, 5, 209],
    [146, 6, 211],
    [143, 7, 214],
    [140, 8, 216],
    [137, 9, 218],
    [134, 10, 220],
    [131, 11, 222],
    [128, 13, 224],
    [125, 14, 226],
    [122, 15, 228],
    [119, 17, 230],
    [116, 18, 232],
    [112, 20, 234],
    [109, 21, 235],
    [106, 23, 237],
    [103, 25, 238],
    [100, 27, 240],
    [98, 29, 241],
    [95, 31, 243],
    [92, 32, 244],
    [89, 35, 245],
    [86, 37, 246],
    [83, 39, 247],
    [80, 41, 248],
    [77, 43, 249],
    [75, 45, 250],
    [72, 48, 251],
    [69, 50, 252],
    [66, 53, 252],
    [64, 55, 253],
    [61, 58, 253],
    [59, 60, 254],
    [56, 63, 254],
    [54, 65, 255],
    [51, 68, 255],
    [49, 71, 255],
    [46, 74, 255],
    [44, 76, 255],
    [42, 79, 255],
    [40, 82, 255],
    [37, 85, 255],
    [35, 88, 254],
    [33, 91, 254],
    [31, 93, 253],
    [29, 96, 253],
    [27, 99, 252],
    [26, 102, 252],
    [24, 105, 251],
    [22, 108, 250]
]

CLASSES = [
    'unlabeled',
    'person',
    'bicycle',
    'car',
    'motorcycle',
    'airplane',
    'bus',
    'train',
    'truck',
    'boat',
    'traffic light',
    'fire hydrant',
    'stop sign',
    'parking meter',
    'bench',
    'bird',
    'cat',
    'dog',
    'horse',
    'sheep',
    'cow',
    'elephant',
    'bear',
    'zebra',
    'giraffe',
    'backpack',
    'umbrella',
    'handbag',
    'tie',
    'suitcase',
    'frisbee',
    'skis',
    'snowboard',
    'sports ball',
    'kite',
    'baseball bat',
    'baseball glove',
    'skateboard',
    'surfboard',
    'tennis racket',
    'bottle',
    'wine glass',
    'cup',
    'fork',
    'knife',
    'spoon',
    'bowl',
    'banana',
    'apple',
    'sandwich',
    'orange',
    'broccoli',
    'carrot',
    'hot dog',
    'pizza',
    'donut',
    'cake',
    'chair',
    'couch',
    'potted plant',
    'bed',
    'dining table',
    'toilet',
    'tv',
    'laptop',
    'mouse',
    'remote',
    'keyboard',
    'cell phone',
    'microwave',
    'oven',
    'toaster',
    'sink',
    'refrigerator',
    'book',
    'clock',
    'vase',
    'scissors',
    'teddy bear',
    'hair drier',
    'toothbrush',
    'banner',
    'blanket',
    'branch',
    'bridge',
    'building-other',
    'bush',
    'cabinet',
    'cage',
    'cardboard',
    'carpet',
    'ceiling-other',
    'ceiling-tile',
    'cloth',
    'clothes',
    'clouds',
    'counter',
    'cupboard',
    'curtain',
    'desk-stuff',
    'dirt',
    'door-stuff',
    'fence',
    'floor-marble',
    'floor-other',
    'floor-stone',
    'floor-tile',
    'floor-wood',
    'flower',
    'fog',
    'food-other',
    'fruit',
    'furniture-other',
    'grass',
    'gravel',
    'ground-other',
    'hill',
    'house',
    'leaves',
    'light',
    'mat',
    'metal',
    'mirror-stuff',
    'moss',
    'mountain',
    'mud',
    'napkin',
    'net',
    'paper',
    'pavement',
    'pillow',
    'plant-other',
    'plastic',
    'platform',
    'playingfield',
    'railing',
    'railroad',
    'river',
    'road',
    'rock',
    'roof',
    'rug',
    'salad',
    'sand',
    'sea',
    'shelf',
    'sky-other',
    'skyscraper',
    'snow',
    'solid-other',
    'stairs',
    'stone',
    'straw',
    'structural-other',
    'table',
    'tent',
    'textile-other',
    'towel',
    'tree',
    'vegetable',
    'wall-brick',
    'wall-concrete',
    'wall-other',
    'wall-panel',
    'wall-stone',
    'wall-tile',
    'wall-wood',
    'water-other',
    'waterdrops',
    'window-blind',
    'window-other',
    'wood',
    'other'
]
